Fix parsing of the `--eval` CLI option (#237)
This patch fixes a bug in the CLI option parser that parses the argument
to `--eval` twice, causing runtime initialization to interpret the
argument as a script path, rather than an inline script. This is
currently causing an example invocation in the README to fail:

```
wasmtime -S http starling.wasm -e "console.log('hello world')"

ReferenceError: Error loading module "console.log('hello world')"
(resolved path "console.log('hello world')"): No such file or directory
```